GData:
  legend: 'Data'
  marker-size: 0.6

GWJets:
  fill-color: '#ff9933'
  legend: 'WJets'

Gttbkg:
  fill-color: '#ff6666'
  legend: 'ttbkg'

GttX:
  fill-color: '#ff66ff'
  legend: 'ttX'

GZJets:
  fill-color: '#000099'
  legend: 'ZJets'

GSingleT:
  fill-color: '#990099'
  legend: 'SingleT'

GVV:
  fill-color: '#00cccc'
  legend: 'VV'

GQCD:
  fill-color: '#d0cfd4'
  legend: 'QCD'

Gttbb:
  fill-color: '#330000'
  legend: 'ttbb'

Gttbj:
  fill-color: '#660000'
  legend: 'ttbj'

Gttcc:
  fill-color: '#990000'
  legend: 'ttcc'

GttLF:
  fill-color: '#cc0000'
  legend: 'ttLF'
