'root18_test/hist_Nosys_DataSingleMu.root':
  type: data
  legend: 'Data'
  pretty-name: 'DataMu'
  marker-size: 0.6
  group: GData

'root18_test/hist_Nosys_DataSingleEG.root':
  type: data
  legend: 'Data'
  pretty-name: 'DataEG'
  marker-size: 0.6
  group: GData

'root18_test/hist_Nosys_ttZToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttZToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.5297
  generated-events: 355226.0
  fill-color: '#ff66ff'
  group: GttX
  order: 12

'root18_test/hist_Nosys_ttZToLLNuNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttZToLLNuNu_aMCatNLOMadspinPythia'
  cross-section: 0.2529
  generated-events: 6274046.0
  fill-color: '#ff66ff'
  group: GttX
  order: 13

'root18_test/hist_Nosys_ttWToQQ_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToQQ_aMCatNLOMadspinPythia'
  cross-section: 0.2043
  generated-events: 458226.0
  fill-color: '#ff66ff'
  group: GttX
  order: 10

'root18_test/hist_Nosys_ttWToLNu_aMCatNLOMadspinPythia.root':
  type: mc
  pretty-name: 'ttWToLNu_aMCatNLOMadspinPythia'
  cross-section: 0.2043
  generated-events: 2686095.0
  fill-color: '#ff66ff'
  group: GttX
  order: 11

'root18_test/hist_Nosys_ttHTobb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHTobb_PowhegPythia'
  cross-section: 0.2923
  generated-events: 11590377.0
  fill-color: '#ff66ff'
  group: GttX
  order: 8

'root18_test/hist_Nosys_ttHToNonbb_PowhegPythia.root':
  type: mc
  pretty-name: 'ttHToNonbb_PowhegPythia'
  cross-section: 0.2151
  generated-events: 7368333.0
  fill-color: '#ff66ff'
  group: GttX
  order: 9

'root18_test/hist_Nosys_ZZ_Pythia.root':
  type: mc
  pretty-name: 'ZZ_Pythia'
  cross-section: 16.523
  generated-events: 1979000.0
  fill-color: '#00cccc'
  group: GVV
  order: 21

'root18_test/hist_Nosys_ZJets_M50_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'ZJets_M50_aMCatNLOPythia'
  cross-section: 6225.42
  generated-events: 100114403.0
  fill-color: '#000099'
  group: GZJets
  order: 22

'root18_test/hist_Nosys_ZJets_M10to50_MadgraphPythia.root':
  type: mc
  pretty-name: 'ZJets_M10to50_MadgraphPythia'
  cross-section: 18610.0
  generated-events: 39360792.0
  fill-color: '#000099'
  group: GZJets
  order: 23

'root18_test/hist_Nosys_WZ_Pythia.root':
  type: mc
  pretty-name: 'WZ_Pythia'
  cross-section: 47.13
  generated-events: 3885000.0
  fill-color: '#00cccc'
  group: GVV
  order: 20

'root18_test/hist_Nosys_WW_Pythia.root':
  type: mc
  pretty-name: 'WW_Pythia'
  cross-section: 118.7
  generated-events: 7850000.0
  fill-color: '#00cccc'
  group: GVV
  order: 19

'root18_test/hist_Nosys_WJetsToLNu_MadgraphPythia.root':
  type: mc
  pretty-name: 'WJetsToLNu_MadgraphPythia'
  cross-section: 61526.7
  generated-events: 70966439.0
  fill-color: '#ff9933'
  legend: 'WJets'
  order: 24

'root18_test/hist_Nosys_TTLL_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTLL_PowhegPythiaBkg'
  cross-section: 88.29
  generated-events: 63791484.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 5

'root18_test/hist_Nosys_TTLJ_PowhegPythia_ttother.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttother'
  cross-section: 365.34
  generated-events: 100728756.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 4

'root18_test/hist_Nosys_TTLJ_PowhegPythia_ttcc.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttcc'
  cross-section: 365.34
  generated-events: 100728756.0
  fill-color: '#990000'
  legend: 'ttcc'
  order: 2

'root18_test/hist_Nosys_TTLJ_PowhegPythia_ttbj.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbj'
  cross-section: 365.34
  generated-events: 100728756.0
  fill-color: '#660000'
  legend: 'ttbj'
  order: 1

'root18_test/hist_Nosys_TTLJ_PowhegPythia_ttbb.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttbb'
  cross-section: 365.34
  generated-events: 100728756.0
  fill-color: '#330000'
  legend: 'ttbb'
  order: 0

'root18_test/hist_Nosys_TTLJ_PowhegPythia_ttLF.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythia_ttLF'
  cross-section: 365.34
  generated-events: 100728756.0
  fill-color: '#cc0000'
  legend: 'ttLF'
  order: 3

'root18_test/hist_Nosys_TTLJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTLJ_PowhegPythiaBkg'
  cross-section: 365.34
  generated-events: 100728756.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 6

'root18_test/hist_Nosys_TTJJ_PowhegPythiaBkg.root':
  type: mc
  pretty-name: 'TTJJ_PowhegPythiaBkg'
  cross-section: 377.96
  generated-events: 132725582.0
  fill-color: '#ff6666'
  group: GttBkg
  order: 7

'root18_test/hist_Nosys_SingleTop_t_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTop_t_PowhegPythia'
  cross-section: 136.02
  generated-events: 144094782.0
  fill-color: '#990099'
  group: GSingleT
  order: 14

'root18_test/hist_Nosys_SingleTop_tW_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTop_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 9553912.0
  fill-color: '#990099'
  group: GSingleT
  order: 15

'root18_test/hist_Nosys_SingleTop_s_aMCatNLOPythia.root':
  type: mc
  pretty-name: 'SingleTop_s_aMCatNLOPythia'
  cross-section: 3.36
  generated-events: 12447484.0
  fill-color: '#990099'
  group: GSingleT
  order: 16

'root18_test/hist_Nosys_SingleTbar_t_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTbar_t_PowhegPythia'
  cross-section: 80.95
  generated-events: 74227130.0
  fill-color: '#990099'
  group: GSingleT
  order: 17

'root18_test/hist_Nosys_SingleTbar_tW_PowhegPythia.root':
  type: mc
  pretty-name: 'SingleTbar_tW_PowhegPythia'
  cross-section: 35.85
  generated-events: 7588180.0
  fill-color: '#990099'
  group: GSingleT
  order: 18

'root18_test/hist_Nosys_QCD_Pt-15to20_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-15to20_MuEnriched'
  cross-section: 3819570.0
  generated-events: 4576061.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 29

'root18_test/hist_Nosys_QCD_Pt-20to30_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-20to30_MuEnriched'
  cross-section: 2960198.4
  generated-events: 30612338.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 30

'root18_test/hist_Nosys_QCD_Pt-50to80_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-50to80_MuEnriched'
  cross-section: 437504.1
  generated-events: 20268872.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 31

'root18_test/hist_Nosys_QCD_Pt-80to120_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-80to120_MuEnriched'
  cross-section: 106033.6648
  generated-events: 25039361.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 32

'root18_test/hist_Nosys_QCD_Pt-120to170_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-120to170_MuEnriched'
  cross-section: 25190.51514
  generated-events: 20682254.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 33

'root18_test/hist_Nosys_QCD_Pt-170to300_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-170to300_MuEnriched'
  cross-section: 8654.49315
  generated-events: 35978539.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 34

'root18_test/hist_Nosys_QCD_Pt-300to470_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-300to470_MuEnriched'
  cross-section: 797.35269
  generated-events: 28996145.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 35

'root18_test/hist_Nosys_QCD_Pt-470to600_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-470to600_MuEnriched'
  cross-section: 79.02553776
  generated-events: 20003034.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 36

'root18_test/hist_Nosys_QCD_Pt-600to800_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-600to800_MuEnriched'
  cross-section: 25.09505908
  generated-events: 16618977.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 37

'root18_test/hist_Nosys_QCD_Pt-1000toInf_MuEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-1000toInf_MuEnriched'
  cross-section: 1.62131692
  generated-events: 10719790.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 38

'root18_test/hist_Nosys_QCD_Pt-15to20_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-15to20_EMEnriched'
  cross-section: 2302200.0
  generated-events: 14578212.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 39

'root18_test/hist_Nosys_QCD_Pt-20to30_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-20to30_EMEnriched'
  cross-section: 5352960.0
  generated-events: 14255377.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 40

'root18_test/hist_Nosys_QCD_Pt-30to50_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-30to50_EMEnriched'
  cross-section: 9928000.0
  generated-events: 15086084.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 41

'root18_test/hist_Nosys_QCD_Pt-50to80_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-50to80_EMEnriched'
  cross-section: 2890800.0
  generated-events: 10798233.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 42

'root18_test/hist_Nosys_QCD_Pt-80to120_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-80to120_EMEnriched'
  cross-section: 350000.0
  generated-events: 9648791.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 43

'root18_test/hist_Nosys_QCD_Pt-120to170_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-120to170_EMEnriched'
  cross-section: 62964.0
  generated-events: 9964143.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 44

'root18_test/hist_Nosys_QCD_Pt-170to300_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-170to300_EMEnriched'
  cross-section: 18810.0
  generated-events: 3712174.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 45

'root18_test/hist_Nosys_QCD_Pt-300toInf_EMEnriched.root':
  type: mc
  pretty-name: 'QCD_Pt-300toInf_EMEnriched'
  cross-section: 1350.0
  generated-events: 2901355.0
  fill-color: '#d0cfd4'
  group: GQCD
  order: 46

